[mongodb]
localhost

[catalogue]
catalogue.ellamma.fun

[redis]
redis.ellamma.fun

[user]
user.ellamma.fun

[cart]
cart.ellamma.fun

[mysql]
mysql.ellamma.fun

[shipping]
shipping.ellamma.fun

[rabbitmq]
rabbitmq.ellamma.fun

[payment]
payment.ellamma.fun

[frontend]
frontend.ellamma.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321