# copy rabbitmq repo
- name: copy rabbitmq repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

# install the rabbitmq server
- name: install the rabbitmq server
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

# enable and start the rabbitmq server
- name: enable and start the rabbitmq server
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

# create rabbitmq username and password
- name: create rabbitmq username and password
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
    - vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
    state: present